import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Contactbar";
import {config} from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Matthew Ameh | Freelancer Developer",
  description: "Generated by Matthew Ameh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
       <div className='flex flex-col h-screen max-h-screen fonts'>
        <div className='overflow-y-auto flex-grow bg-page text-default-text'>{children}</div></div> 
      </body>
    </html>
  );
}
